### ISSUE TITLE
U60可以登录，但是会不断登录注销

### ISSUE THREAD

**Issue by charli2014** [drcoms/drcom-HC5661-1s-patch#1]
我们学校使用的U60，使用此程序可以登录，但是会不断的登录注销。
![2014-06-23_132344](https://cloud.githubusercontent.com/assets/7960986/3354060/577a88ba-fa97-11e3-9fa0-e9c87943d6c3.jpg)

下面是登陆时的调试显示：
[challenge] recv 02027f0ae2a8a80000000100f003e8f000000000ac18cd040400a8a20000294d4d3f00000000d802000000000000000000000000000000000000000000000000000000000000000000000000
[DEBUG] challenge:
02027f0ae2a8a80000000100f003e8f000000000ac18cd040400a8a20000294d4d3f00000000d802000000000000000000000000000000000000000000000000000000000000000000000000
[challenge] challenge packet sent.
[mkpkt] 0301001c65f93a78d31b4c4fc1649404360a6b1b3230313034333933000000000000000000000000000000000000000000000000000000002002dd71d97dc59bd9df0d329bb566aa642aeed415f0ce280100000000000000000000000000000000227685387592748901000000004472636f6d0000000000000000000000000000000000000000000000000000000808080800000000000000000000000000000000940000000500000001000000280a0000020000004c696e75780000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00020c904cb9c70000b888e30516800000e913
[login] send 0301001c65f93a78d31b4c4fc1649404360a6b1b3230313034333933000000000000000000000000000000000000000000000000000000002002dd71d97dc59bd9df0d329bb566aa642aeed415f0ce280100000000000000000000000000000000227685387592748901000000004472636f6d0000000000000000000000000000000000000000000000000000000808080800000000000000000000000000000000940000000500000001000000280a0000020000004c696e75780000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00020c904cb9c70000b888e30516800000e913
[login] recv 0400000500c95b000022511605ffffffffff00000000004472636fcaca00a33c4aac18cd0401e5b0050b00010000003ac80a00ffffff0000000000caca0000fffff00000000000caca4000fffff00000000000dac28000fffff00000000000dbdd6000ffffe00000000000dec68000ffffe00000000000b4558000ffff800000000000c0a80000ffff000000000000ac100000fff00000000000000a000000ff0000000100000000000000000000000110
[login] packet sent.
[login] loged in
[login] login sent
package_tail 4472636fcaca00a33c4aac18cd0401e5
starting to empty socket buffer
recived sth unexcepted 4d3a633a687474703a2f2f6a6764772e6371752e6564752e636e2f68746d6c2f7765622f313534352e68746d
exception in empty_socket_buffer
emptyed
[keep_alive1] send ff65f93a78d31b4c4fc1649404360a6b1b0000004472636fcaca00a33c4aac18cd0401e50a6800000000
[keep-alive1] recv 0701100006000a686833f705ac18cd04a8a20000294d4d3f00000000d8020000030000000000000005000000c95b000022511605ffffffffffffffffffffffff
[keep-alive2] send1 070028000b010f272f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv1 070010010b06d8022f12000000000000a8a20000294d4d3f00000000d80200004d5a90000300000004000000ffff0000b800000000000000400000000000000000000000000000000000000000000000000000000000000000000000080100000e1fba0e00b409cd21b8014ccd21546869732070726f6772616d2063616e6e6f742062652072756e20696e20444f53206d6f64652e0d0d0a2400000000000000be4ff959fa2e970afa2e970afa2e970aa30d840af82e970a81329b0afe2e970a7926ca0af02e970a7932990af82e970a95319c0afb2e970a95319d0aff2e970a9531930af82e970afa2e960a492e970acc08930af92e970acc089c0af22e970a3d28910afb2e970a050e930af92e970a
[keep-alive2] send2 070128000b01dc022f12000000000000000000000000000000000000000000000000000000000000
[keep-alive2] recv2 070110010b06d8022f12000000000000a8a20000294d4d3f00000000d80200004d5a90000300000004000000ffff0000b800000000000000400000000000000000000000000000000000000000000000000000000000000000000000080100000e1fba0e00b409cd21b8014ccd21546869732070726f6772616d2063616e6e6f742062652072756e20696e20444f53206d6f64652e0d0d0a2400000000000000be4ff959fa2e970afa2e970afa2e970aa30d840af82e970a81329b0afe2e970a7926ca0af02e970a7932990af82e970a95319c0afb2e970a95319d0aff2e970a9531930af82e970afa2e960a492e970acc08930af92e970acc089c0af22e970a3d28910afb2e970a050e930af92e970a
[keep-alive2] send3 070228000b03dc022f12000000000000a8a200000000000000000000000000000000000000000000
Traceback (most recent call last):
  File "/usr/bin/wired.py", line 318, in <module>
    main()
  File "/usr/bin/wired.py", line 316, in main
    keep_alive2(SALT,package_tail,password,server)
  File "/usr/bin/wired.py", line 148, in keep_alive2
    data, address = s.recvfrom(1024)
socket.timeout: timed out

这种是不是不匹配U60导致的？

**Comment by emizos** [comment]
在电脑上运行wired.py能成功登陆，但是在路由器上运行python /usr/bin/wired.py，就出现了下面的错误。（重庆大学  drcom5.20版）

[challenge] timeout, retrying...
 File "/usr/bin/wired.py", line 321, in <module>
    main()
  File "/usr/bin/wired.py", line 311, in main
    package_tail = login(username, password, server)
  File "/usr/bin/wired.py", line 251, in login
    salt = challenge(svr,time.time()+random.randint(0xF,0xFF))
  File "/usr/bin/wired.py", line 51, in challenge
    log('[challenge] timeout, retrying...')
  File "/usr/bin/wired.py", line 41, in log
    f.write(s + '\n')

**Comment by 500mstar** [comment]
我学校的登陆了没两下就下线了，D版的，不知道要修改哪里，附上运行的日志，还有抓包数据

![1](https://cloud.githubusercontent.com/assets/18138820/14103513/267d5cea-f5d3-11e5-9688-c44db1a535b8.jpg)
![2](https://cloud.githubusercontent.com/assets/18138820/14103514/267fb490-f5d3-11e5-98df-6a66337c5a64.jpg)
